# -*- coding: utf-8 -*-
"""Dynamic Data Ingestion and Storage in HDFS with Automated Hive Integration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a90FEE44nia3S9pI_8i-usIAtSiQ2GXG

**Problem Statement:**

The task aims to fetch data from a specified link, store it in HDFS, and create a Hive table to visualize the data. Initially, ensuring access to the provided link and successful data retrieval is essential. Subsequently, determining the data format and schema, if structured, is pivotal. Utilizing tools like wget or curl for data retrieval and HDFS CLI for storage follows. Finally, creating a Hive table, loading data, and verifying correctness conclude the task, with an optional script for automation.
"""

link = 'https://www2.census.gov/programs-surveys/popest/datasets/2020-2024/counties/totals/co-est2024-alldata.csv'

"""**Platform - Cloudera (HDFS & HIVE Pre-installed)**

**Verify accessibility and download capability from the provided link.
Determine the data format and structure (single or multiple files, structured or unstructured).
Employ wget or curl to download data and pipe output to HDFS CLI (hadoop fs -put) for storage.**

Tried Downloading file from link but some issue of SSL Connection failure

**Make folder named gayatri_guvi in HDFS**

hadoop fs -mkdir gayatri_guvi

**Copy CSV file from hdfs to hdfs folder named gayatri_guvi**

hadoop fs -copyFromLocal product_data.csv gayatri_guvi

**Check if CSV file is loaded into gayatri_guvi?**

hadoop fs -ls gayatri_guvi

**Enter into HIVE Environment**

Type hive and enter

**Create database in hive**

create database guvi_proj_6;

**Use database**

use guvi_proj_6;

**Create table in database**

CREATE TABLE IF NOT EXISTS product_data (
    id INT,
    name STRING,
    price DOUBLE,
    city STRING,
    ownership STRING
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

**Load CSV file data into table in hive**

LOAD DATA INPATH '/user/training/gayatri_guvi/product_data.csv' INTO TABLE product_data;

**Check if data is loaded into table or not**

select * from product_data;
"""